// <auto-generated />
namespace OnlineJobPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PostPrePhdexpandpapersadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostPrePhdexpandpapersadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202402250946350_Post/Pre Phd exp and papers added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
